#modloaded gregtech gtadditions tfc

// Author : SpeeeDCraft, ACGaming
// Mod required : GregTech, Gregicality, TerraFirmaCraft
// Scripts required : -

import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IItemTransformer;
import crafttweaker.liquid.ILiquidStack;
import crafttweaker.oredict.IOreDictEntry;
import mods.gregtech.recipe.PBFRecipeBuilder;
import mods.gregtech.recipe.RecipeMap;
import mods.gregtech.recipe.RecipeMaps;
import mods.jei.JEI;

val alloy_smelter as RecipeMap = RecipeMap.getByName("alloy_smelter");
val arc_furnace as RecipeMap = RecipeMap.getByName("arc_furnace");
val assembler as RecipeMap = RecipeMap.getByName("assembler");
val bio_reactor as RecipeMap = RecipeMap.getByName("bio_reactor");
val blast_furnace = mods.gregtech.recipe.RecipeMap.getByName("blast_furnace");
val brewer as RecipeMap = RecipeMap.getByName("brewer");
val centrifuge as RecipeMap = RecipeMap.getByName("centrifuge");
val chemical_bath as RecipeMap = RecipeMap.getByName("chemical_bath");
val chemical_plant as RecipeMap = RecipeMap.getByName("chemical_plant");
val chemical_reactor as RecipeMap = RecipeMap.getByName("chemical_reactor");
val compressor as RecipeMap = RecipeMap.getByName("compressor");
val cutting_saw as RecipeMap = RecipeMap.getByName("cutting_saw");
val distillery as RecipeMap = RecipeMap.getByName("distillery");
val electrolyzer as RecipeMap = RecipeMap.getByName("electrolyzer");
val extractor as RecipeMap = RecipeMap.getByName("extractor");
val extruder as RecipeMap = RecipeMap.getByName("extruder");
val fermenter as RecipeMap = RecipeMap.getByName("fermenter");
val fluid_extractor as RecipeMap = RecipeMap.getByName("fluid_extractor");
val fluid_heater as RecipeMap = RecipeMap.getByName("fluid_heater");
val fluid_solidifier as RecipeMap = RecipeMap.getByName("fluid_solidifier");
val forge_hammer as RecipeMap = RecipeMap.getByName("forge_hammer");
val green_house as RecipeMap = RecipeMap.getByName("green_house");
val icompressor as RecipeMap = RecipeMap.getByName("implosion_compressor");
val large_centrifuge as RecipeMap = RecipeMap.getByName("large_centrifuge");
val large_chemical_reactor as RecipeMap = RecipeMap.getByName("large_chemical_reactor");
val large_mixer as RecipeMap = RecipeMap.getByName("large_mixer");
val lathe as RecipeMap = RecipeMap.getByName("lathe");
val macerator as RecipeMap = RecipeMap.getByName("macerator");
val mixer as RecipeMap = RecipeMap.getByName("mixer");
val packer as RecipeMap = RecipeMap.getByName("packer");
val thermal_centrifuge as RecipeMap = RecipeMap.getByName("thermal_centrifuge");

// JEI
JEI.removeAndHide(<gregtech:machine:807>);
JEI.removeAndHide(<gregtech:machine:808>);
JEI.removeAndHide(<gregtech:machine:2553>);
JEI.removeAndHide(<gregtech:machine:510>);
JEI.removeAndHide(<gregtech:metal_casing:1>);
JEI.removeAndHide(<gregtech:meta_item_1:2356>);
JEI.removeAndHide(<gtadditions:ga_meta_item:32037>);
JEI.removeAndHide(<gtadditions:ga_meta_item:32038>);
JEI.removeAndHide(<gregtech:meta_item_2:32015>);

// ALLOY SMELTER
alloy_smelter.recipeBuilder().inputs(<ore:dustRawRubber> * 8, <ore:dustSulfur> * 4).outputs(<ore:ingotRubber>.firstItem * 1).duration(300).EUt(8).buildAndRegister();
alloy_smelter.recipeBuilder().inputs(<ore:ingotRubber> * 2).notConsumable(<metaitem:shape.mold.plate>).outputs(<ore:plateRubber>.firstItem * 1).duration(140).EUt(8).buildAndRegister();

// ARC FURNACE
arc_furnace.recipeBuilder().inputs(<gregtech:machine:802>).fluidInputs([<liquid:oxygen> * 500]).outputs(<gregtech:meta_item_1:10095>*10).EUt(8).duration(400).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:803>).fluidInputs([<liquid:oxygen> * 500]).outputs(<gregtech:meta_item_1:10184>*10).EUt(30).duration(400).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:804>).fluidInputs([<liquid:oxygen> * 500]).outputs(<gregtech:meta_item_1:10183>*10).EUt(120).duration(400).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:805>).fluidInputs([<liquid:oxygen> * 500]).outputs(<gregtech:meta_item_1:10072>*10).EUt(500).duration(400).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:806>).fluidInputs([<liquid:oxygen> * 500]).outputs(<gregtech:meta_item_1:10235>*10).EUt(1560).duration(400).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:812>).fluidInputs([<liquid:oxygen> * 150]).outputs(<gregtech:meta_item_1:10095>*3).duration(750).EUt(34).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:813>).fluidInputs([<liquid:oxygen> * 150]).outputs(<gregtech:meta_item_1:10184>*3).duration(750).EUt(34).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:814>).fluidInputs([<liquid:oxygen> * 150]).outputs(<gregtech:meta_item_1:10183>*3).duration(750).EUt(34).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:815>).fluidInputs([<liquid:oxygen> * 150]).outputs(<gregtech:meta_item_1:10072>*3).duration(750).EUt(34).buildAndRegister();
arc_furnace.recipeBuilder().inputs(<gregtech:machine:816>).fluidInputs([<liquid:oxygen> * 150]).outputs(<gregtech:meta_item_1:10235>*3).duration(750).EUt(34).buildAndRegister();

// ASSEMBLER
assembler.findRecipe(16, [<gregtech:meta_item_1:12001>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12072>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12183>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12184>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12197>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12207>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12235>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12311>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.findRecipe(16, [<gregtech:meta_item_1:12859>*8, <gregtech:meta_item_1:32766>.withTag({Configuration: 8})], null).remove();
assembler.recipeBuilder().inputs(<ore:plateAluminium>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:2>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateIron>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateNeutronium>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:9>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateOsmiridium>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:7>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateRhodiumPlatedPalladium>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:6>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateStainlessSteel>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:3>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateSteel>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:1>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateTitanium>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:4>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateTritanium>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:8>).duration(20).EUt(16).buildAndRegister();
assembler.recipeBuilder().inputs(<ore:plateTungstenSteel>*6).notConsumable(<gregtech:meta_item_1:32766>.withTag({Configuration: 8})).outputs(<gregtech:machine_casing:5>).duration(20).EUt(16).buildAndRegister();

// CHEMICAL BATH
chemical_bath.recipeBuilder().inputs(<tfc:raw/marble>).fluidInputs([<liquid:hot_water> * 1000]).outputs(<astralsorcery:blockmarble>).duration(20).EUt(2).buildAndRegister();

// COMPRESSOR
compressor.recipeBuilder().inputs(<ore:gemDiamond> * 9).outputs(<minecraft:diamond_block>).duration(400).EUt(2).buildAndRegister();
compressor.recipeBuilder().inputs(<ore:gemEmerald> * 9).outputs(<minecraft:emerald_block>).duration(400).EUt(2).buildAndRegister();
compressor.recipeBuilder().inputs(<ore:gemLapis> * 9).outputs(<minecraft:lapis_block>).duration(400).EUt(2).buildAndRegister();

// FLUID EXTRACTOR
fluid_extractor.recipeBuilder().inputs(<minecraft:magma>).fluidOutputs(<fluid:lava> * 750).EUt(140).duration(220).buildAndRegister();
fluid_extractor.recipeBuilder().inputs(<ore:netherrack>).fluidOutputs(<fluid:lava> * 250).EUt(140).duration(330).buildAndRegister();

// FLUID HEATER
fluid_heater.recipeBuilder().notConsumable(<metaitem:circuit.integrated>.withTag({Configuration: 1})).fluidInputs(<liquid:liquid_oxygen> * 100).fluidOutputs(<liquid:oxygen> * 1000)  .duration(400).EUt(32).buildAndRegister();

// FORGE HAMMER
forge_hammer.recipeBuilder().inputs([<ore:gravel> * 1]).outputs(<minecraft:flint> * 1).duration(45).EUt(5).buildAndRegister();
forge_hammer.recipeBuilder().inputs([<ore:sugarcane> * 3]).outputs(<ore:dustPaper>.firstItem * 2).duration(105).EUt(4).buildAndRegister();

// FURNACE
furnace.addRecipe(<tfc:metal/ingot/wrought_iron>, <ore:dustIron>);

// IMPLOSION COMPRESSOR
icompressor.recipeBuilder().inputs(<ore:ingotSteel> * 2, <ore:ingotCarbon> * 1).property("explosives", 1).outputs(<contenttweaker:part_plate_basic> * 1).duration(50).EUt(32).buildAndRegister();
icompressor.recipeBuilder().inputs(<ore:plateLead> * 2, <ore:ingotCarbon> * 1).property("explosives", 1).outputs(<contenttweaker:part_plate_advanced> * 1).duration(50).EUt(64).buildAndRegister();
icompressor.recipeBuilder().inputs(<ore:plateUranium235> * 2, <ore:ingotLead> * 3).property("explosives", 1).outputs(<contenttweaker:part_plate_elite> * 2).duration(50).EUt(256).buildAndRegister();
icompressor.recipeBuilder().inputs(<ore:plateZinc> * 2, <ore:ingotCarbon> * 1).property("explosives", 1).outputs(<contenttweaker:part_plate_du> * 1).duration(50).EUt(128).buildAndRegister();

// MIXER
mixer.recipeBuilder().inputs(<ore:sand>*4,<ore:gravel>*4).outputs(<tfc:aggregate>*8).duration(20).EUt(4).buildAndRegister();

// RECIPES
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iron"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iron"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iron"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "rhodium_plated_palladium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iron"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "rhodium_plated_palladium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<ore:toolHeadHammerAluminium>);
recipes.remove(<ore:toolHeadHammerAmethyst>);
recipes.remove(<ore:toolHeadHammerBismuthBronze>);
recipes.remove(<ore:toolHeadHammerBlackBronze>);
recipes.remove(<ore:toolHeadHammerBlackSteel>);
recipes.remove(<ore:toolHeadHammerBlueSteel>);
recipes.remove(<ore:toolHeadHammerBlueTopaz>);
recipes.remove(<ore:toolHeadHammerBrass>);
recipes.remove(<ore:toolHeadHammerBronze>);
recipes.remove(<ore:toolHeadHammerChrome>);
recipes.remove(<ore:toolHeadHammerCobalt>);
recipes.remove(<ore:toolHeadHammerCobaltBrass>);
recipes.remove(<ore:toolHeadHammerDamascusSteel>);
recipes.remove(<ore:toolHeadHammerDarmstadtium>);
recipes.remove(<ore:toolHeadHammerDiamond>);
recipes.remove(<ore:toolHeadHammerDuranium>);
recipes.remove(<ore:toolHeadHammerEmerald>);
recipes.remove(<ore:toolHeadHammerEnderium>);
recipes.remove(<ore:toolHeadHammerGarnetRed>);
recipes.remove(<ore:toolHeadHammerGarnetYellow>);
recipes.remove(<ore:toolHeadHammerGreenSapphire>);
recipes.remove(<ore:toolHeadHammerHsse>);
recipes.remove(<ore:toolHeadHammerHssg>);
recipes.remove(<ore:toolHeadHammerHsss>);
recipes.remove(<ore:toolHeadHammerInvar>);
recipes.remove(<ore:toolHeadHammerIridium>);
recipes.remove(<ore:toolHeadHammerIron>);
recipes.remove(<ore:toolHeadHammerMagnalium>);
recipes.remove(<ore:toolHeadHammerManganese>);
recipes.remove(<ore:toolHeadHammerMolybdenum>);
recipes.remove(<ore:toolHeadHammerNaquadah>);
recipes.remove(<ore:toolHeadHammerNaquadahAlloy>);
recipes.remove(<ore:toolHeadHammerNaquadahEnriched>);
recipes.remove(<ore:toolHeadHammerNeodymium>);
recipes.remove(<ore:toolHeadHammerNeutronium>);
recipes.remove(<ore:toolHeadHammerOlivine>);
recipes.remove(<ore:toolHeadHammerOpal>);
recipes.remove(<ore:toolHeadHammerOsmiridium>);
recipes.remove(<ore:toolHeadHammerOsmium>);
recipes.remove(<ore:toolHeadHammerPalladium>);
recipes.remove(<ore:toolHeadHammerPigIron>);
recipes.remove(<ore:toolHeadHammerRedSteel>);
recipes.remove(<ore:toolHeadHammerRoseGold>);
recipes.remove(<ore:toolHeadHammerRuby>);
recipes.remove(<ore:toolHeadHammerSapphire>);
recipes.remove(<ore:toolHeadHammerStainlessSteel>);
recipes.remove(<ore:toolHeadHammerSteel>);
recipes.remove(<ore:toolHeadHammerSterlingSilver>);
recipes.remove(<ore:toolHeadHammerTanzanite>);
recipes.remove(<ore:toolHeadHammerThorium>);
recipes.remove(<ore:toolHeadHammerTitanium>);
recipes.remove(<ore:toolHeadHammerTopaz>);
recipes.remove(<ore:toolHeadHammerTritanium>);
recipes.remove(<ore:toolHeadHammerTungsten>);
recipes.remove(<ore:toolHeadHammerTungstenCarbide>);
recipes.remove(<ore:toolHeadHammerTungstenSteel>);
recipes.remove(<ore:toolHeadHammerUltimet>);
recipes.remove(<ore:toolHeadHammerUranium235>);
recipes.remove(<ore:toolHeadHammerUranium>);
recipes.remove(<ore:toolHeadHammerVanadiumSteel>);
recipes.remove(<ore:toolHeadHammerVinteum>);
recipes.remove(<ore:toolHeadHammerWroughtIron>);
recipes.remove(<ore:toolHeadSawAluminium>);
recipes.remove(<ore:toolHeadSawAmethyst>);
recipes.remove(<ore:toolHeadSawBismuthBronze>);
recipes.remove(<ore:toolHeadSawBlackBronze>);
recipes.remove(<ore:toolHeadSawBlackSteel>);
recipes.remove(<ore:toolHeadSawBlueSteel>);
recipes.remove(<ore:toolHeadSawBlueTopaz>);
recipes.remove(<ore:toolHeadSawBrass>);
recipes.remove(<ore:toolHeadSawBronze>);
recipes.remove(<ore:toolHeadSawChrome>);
recipes.remove(<ore:toolHeadSawCobalt>);
recipes.remove(<ore:toolHeadSawCobaltBrass>);
recipes.remove(<ore:toolHeadSawDamascusSteel>);
recipes.remove(<ore:toolHeadSawDarmstadtium>);
recipes.remove(<ore:toolHeadSawDiamond>);
recipes.remove(<ore:toolHeadSawDuranium>);
recipes.remove(<ore:toolHeadSawEmerald>);
recipes.remove(<ore:toolHeadSawEnderium>);
recipes.remove(<ore:toolHeadSawGarnetRed>);
recipes.remove(<ore:toolHeadSawGarnetYellow>);
recipes.remove(<ore:toolHeadSawGreenSapphire>);
recipes.remove(<ore:toolHeadSawHsse>);
recipes.remove(<ore:toolHeadSawHssg>);
recipes.remove(<ore:toolHeadSawHsss>);
recipes.remove(<ore:toolHeadSawInvar>);
recipes.remove(<ore:toolHeadSawIridium>);
recipes.remove(<ore:toolHeadSawIron>);
recipes.remove(<ore:toolHeadSawMagnalium>);
recipes.remove(<ore:toolHeadSawManganese>);
recipes.remove(<ore:toolHeadSawMolybdenum>);
recipes.remove(<ore:toolHeadSawNaquadah>);
recipes.remove(<ore:toolHeadSawNaquadahAlloy>);
recipes.remove(<ore:toolHeadSawNaquadahEnriched>);
recipes.remove(<ore:toolHeadSawNeodymium>);
recipes.remove(<ore:toolHeadSawNeutronium>);
recipes.remove(<ore:toolHeadSawOlivine>);
recipes.remove(<ore:toolHeadSawOpal>);
recipes.remove(<ore:toolHeadSawOsmiridium>);
recipes.remove(<ore:toolHeadSawOsmium>);
recipes.remove(<ore:toolHeadSawPalladium>);
recipes.remove(<ore:toolHeadSawPigIron>);
recipes.remove(<ore:toolHeadSawRedSteel>);
recipes.remove(<ore:toolHeadSawRoseGold>);
recipes.remove(<ore:toolHeadSawRuby>);
recipes.remove(<ore:toolHeadSawSapphire>);
recipes.remove(<ore:toolHeadSawStainlessSteel>);
recipes.remove(<ore:toolHeadSawSteel>);
recipes.remove(<ore:toolHeadSawSterlingSilver>);
recipes.remove(<ore:toolHeadSawTanzanite>);
recipes.remove(<ore:toolHeadSawThorium>);
recipes.remove(<ore:toolHeadSawTitanium>);
recipes.remove(<ore:toolHeadSawTopaz>);
recipes.remove(<ore:toolHeadSawTritanium>);
recipes.remove(<ore:toolHeadSawTungsten>);
recipes.remove(<ore:toolHeadSawTungstenCarbide>);
recipes.remove(<ore:toolHeadSawTungstenSteel>);
recipes.remove(<ore:toolHeadSawUltimet>);
recipes.remove(<ore:toolHeadSawUranium235>);
recipes.remove(<ore:toolHeadSawUranium>);
recipes.remove(<ore:toolHeadSawVanadiumSteel>);
recipes.remove(<ore:toolHeadSawVinteum>);
recipes.remove(<ore:toolHeadSawWroughtIron>);
recipes.removeByRecipeName("gregtech:axe_flint");
recipes.removeByRecipeName("gregtech:casing_invar_heatproof");
recipes.removeByRecipeName("gregtech:casing_lv");
recipes.removeByRecipeName("gregtech:dust_blue_steel");
recipes.removeByRecipeName("gregtech:dust_red_steel");
recipes.removeByRecipeName("gregtech:hoe_flint");
recipes.removeByRecipeName("gregtech:knife_flint");
recipes.removeByRecipeName("gregtech:pickaxe_flint");
recipes.removeByRecipeName("gregtech:shovel_flint");
recipes.removeByRecipeName("gregtech:sword_flint");
recipes.removeShaped(<gregtech:meta_item_1:12780>);
recipes.removeShaped(<ore:plateAbyssalAlloy>);
recipes.removeShaped(<ore:plateAluminium>);
recipes.removeShaped(<ore:plateAmericium>);
recipes.removeShaped(<ore:plateAnnealedCopper>);
recipes.removeShaped(<ore:plateAntimony>);
recipes.removeShaped(<ore:plateBabbittAlloy>);
recipes.removeShaped(<ore:plateBatteryAlloy>);
recipes.removeShaped(<ore:plateBerkelium>);
recipes.removeShaped(<ore:plateBeryllium>);
recipes.removeShaped(<ore:plateBismuthBronze>);
recipes.removeShaped(<ore:plateBlackBronze>);
recipes.removeShaped(<ore:plateBlackSteel>);
recipes.removeShaped(<ore:plateBlueSteel>);
recipes.removeShaped(<ore:plateBrass>);
recipes.removeShaped(<ore:plateBronze>);
recipes.removeShaped(<ore:plateCalifornium>);
recipes.removeShaped(<ore:plateCerium>);
recipes.removeShaped(<ore:plateChrome>);
recipes.removeShaped(<ore:plateCobalt>);
recipes.removeShaped(<ore:plateCobaltBrass>);
recipes.removeShaped(<ore:plateCopper>);
recipes.removeShaped(<ore:plateCupronickel>);
recipes.removeShaped(<ore:plateCurium>);
recipes.removeShaped(<ore:plateDamascusSteel>);
recipes.removeShaped(<ore:plateDarmstadtium>);
recipes.removeShaped(<ore:plateDubnium>);
recipes.removeShaped(<ore:plateDuranium>);
recipes.removeShaped(<ore:plateEglinSteel>);
recipes.removeShaped(<ore:plateEinsteinium>);
recipes.removeShaped(<ore:plateElectrum>);
recipes.removeShaped(<ore:plateEnderium>);
recipes.removeShaped(<ore:plateEpoxid>);
recipes.removeShaped(<ore:plateErbium>);
recipes.removeShaped(<ore:plateEuropium>);
recipes.removeShaped(<ore:plateEvSuperconductorBase>);
recipes.removeShaped(<ore:plateFermium>);
recipes.removeShaped(<ore:plateGallium>);
recipes.removeShaped(<ore:plateGalliumArsenide>);
recipes.removeShaped(<ore:plateGold>);
recipes.removeShaped(<ore:plateGraphene>);
recipes.removeShaped(<ore:plateGraphene>);
recipes.removeShaped(<ore:plateGraphite>);
recipes.removeShaped(<ore:plateGrisium>);
recipes.removeShaped(<ore:plateHastelloyN>);
recipes.removeShaped(<ore:plateHgAlloy>);
recipes.removeShaped(<ore:plateHsse>);
recipes.removeShaped(<ore:plateHssg>);
recipes.removeShaped(<ore:plateHsss>);
recipes.removeShaped(<ore:plateHvSuperconductorBase>);
recipes.removeShaped(<ore:plateIncoloyMa>);
recipes.removeShaped(<ore:plateInconelA>);
recipes.removeShaped(<ore:plateIndiumGalliumPhosphide>);
recipes.removeShaped(<ore:plateInvar>);
recipes.removeShaped(<ore:plateIridium>);
recipes.removeShaped(<ore:plateIron>);
recipes.removeShaped(<ore:plateIronMagnetic>);
recipes.removeShaped(<ore:plateIvSuperconductorBase>);
recipes.removeShaped(<ore:plateKanthal>);
recipes.removeShaped(<ore:plateLead>);
recipes.removeShaped(<ore:plateLithium>);
recipes.removeShaped(<ore:plateLuvSuperconductorBase>);
recipes.removeShaped(<ore:plateMagnalium>);
recipes.removeShaped(<ore:plateMagnesium>);
recipes.removeShaped(<ore:plateManganese>);
recipes.removeShaped(<ore:plateMaragingSteelA>);
recipes.removeShaped(<ore:plateMolybdenum>);
recipes.removeShaped(<ore:plateMvSuperconductorBase>);
recipes.removeShaped(<ore:plateNaquadah>);
recipes.removeShaped(<ore:plateNaquadahAlloy>);
recipes.removeShaped(<ore:plateNaquadahEnriched>);
recipes.removeShaped(<ore:plateNaquadria>);
recipes.removeShaped(<ore:plateNeodymium>);
recipes.removeShaped(<ore:plateNeodymiumMagnetic>);
recipes.removeShaped(<ore:plateNeptunium>);
recipes.removeShaped(<ore:plateNeutronium>);
recipes.removeShaped(<ore:plateNichrome>);
recipes.removeShaped(<ore:plateNickel>);
recipes.removeShaped(<ore:plateNickelZincFerrite>);
recipes.removeShaped(<ore:plateNiobium>);
recipes.removeShaped(<ore:plateNiobiumNitride>);
recipes.removeShaped(<ore:plateNiobiumTitanium>);
recipes.removeShaped(<ore:plateNitinolA>);
recipes.removeShaped(<ore:plateOsmiridium>);
recipes.removeShaped(<ore:plateOsmium>);
recipes.removeShaped(<ore:platePalladium>);
recipes.removeShaped(<ore:platePigIron>);
recipes.removeShaped(<ore:platePlatinum>);
recipes.removeShaped(<ore:platePlutonium241>);
recipes.removeShaped(<ore:platePlutonium>);
recipes.removeShaped(<ore:platePlutoniumRadioactive>);
recipes.removeShaped(<ore:platePolybenzimidazole>);
recipes.removeShaped(<ore:platePolycaprolactam>);
recipes.removeShaped(<ore:platePolyphenyleneSulfide>);
recipes.removeShaped(<ore:platePolystyrene>);
recipes.removeShaped(<ore:platePolytetrafluoroethylene>);
recipes.removeShaped(<ore:platePolyvinylChloride>);
recipes.removeShaped(<ore:platePotassium>);
recipes.removeShaped(<ore:platePotin>);
recipes.removeShaped(<ore:platePraseodymium>);
recipes.removeShaped(<ore:platePromethium>);
recipes.removeShaped(<ore:plateProtactinium>);
recipes.removeShaped(<ore:plateReactorSteel>);
recipes.removeShaped(<ore:plateRedAlloy>);
recipes.removeShaped(<ore:plateRedSteel>);
recipes.removeShaped(<ore:plateReinforcedEpoxyResin>);
recipes.removeShaped(<ore:plateRhodium>);
recipes.removeShaped(<ore:plateRhodiumPlatedPalladium>);
recipes.removeShaped(<ore:plateRoseGold>);
recipes.removeShaped(<ore:plateRubidium>);
recipes.removeShaped(<ore:plateRuthenium>);
recipes.removeShaped(<ore:plateRutherfordium>);
recipes.removeShaped(<ore:plateSamarium>);
recipes.removeShaped(<ore:plateScandium>);
recipes.removeShaped(<ore:plateSilicon>);
recipes.removeShaped(<ore:plateSiliconeRubber>);
recipes.removeShaped(<ore:plateSilver>);
recipes.removeShaped(<ore:plateSodium>);
recipes.removeShaped(<ore:plateSolderingAlloy>);
recipes.removeShaped(<ore:plateStaballoy>);
recipes.removeShaped(<ore:plateStainlessSteel>);
recipes.removeShaped(<ore:plateSteel>);
recipes.removeShaped(<ore:plateSteelMagnetic>);
recipes.removeShaped(<ore:plateStellite>);
recipes.removeShaped(<ore:plateSterlingSilver>);
recipes.removeShaped(<ore:plateStrontium>);
recipes.removeShaped(<ore:plateStyreneButadieneRubber>);
recipes.removeShaped(<ore:plateTalonite>);
recipes.removeShaped(<ore:plateTantalum>);
recipes.removeShaped(<ore:plateTellurium>);
recipes.removeShaped(<ore:plateTerbium>);
recipes.removeShaped(<ore:plateThorium>);
recipes.removeShaped(<ore:plateThulium>);
recipes.removeShaped(<ore:plateTin>);
recipes.removeShaped(<ore:plateTinAlloy>);
recipes.removeShaped(<ore:plateTitanium>);
recipes.removeShaped(<ore:plateTritanium>);
recipes.removeShaped(<ore:plateTumbaga>);
recipes.removeShaped(<ore:plateTungsten>);
recipes.removeShaped(<ore:plateTungstenCarbide>);
recipes.removeShaped(<ore:plateTungstenSteel>);
recipes.removeShaped(<ore:plateUltimet>);
recipes.removeShaped(<ore:plateUranium235>);
recipes.removeShaped(<ore:plateUranium>);
recipes.removeShaped(<ore:plateUraniumRadioactive>);
recipes.removeShaped(<ore:plateUvSuperconductorBase>);
recipes.removeShaped(<ore:plateVanadium>);
recipes.removeShaped(<ore:plateVanadiumGallium>);
recipes.removeShaped(<ore:plateVanadiumSteel>);
recipes.removeShaped(<ore:plateWroughtIron>);
recipes.removeShaped(<ore:plateYtterbium>);
recipes.removeShaped(<ore:plateYttrium>);
recipes.removeShaped(<ore:plateYttriumBariumCuprate>);
recipes.removeShaped(<ore:plateZinc>);
recipes.removeShaped(<ore:plateZinc>);
recipes.removeShaped(<ore:plateZirconium>);
recipes.removeShaped(<ore:plateZirconiumCarbide>);
recipes.removeShaped(<ore:plateZpmSuperconductorBase>);
recipes.replaceAllOccurences(<minecraft:furnace>, <contenttweaker:furnaceblock>);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "Hsse", MaxDurability: 117000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateHsse>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickHsse>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "Hssg", MaxDurability: 17000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateHssg>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickHssg>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "Hsss", MaxDurability: 15000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateHsss>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickHsss>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateAluminium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickAluminium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBismuthBronze>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBismuthBronze>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBlackBronze>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBlackBronze>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBlackSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBlackSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBlueSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBlueSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBrass>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBrass>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBronze>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBronze>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateChrome>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickChrome>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt", MaxDurability: 2200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateCobalt>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickCobalt>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateCobaltBrass>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickCobaltBrass>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "copper", MaxDurability: 150}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateCopper>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickCopper>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateDamascusSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickDamascusSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateDarmstadtium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickDarmstadtium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateDiamond>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickDiamond>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "invar", MaxDurability: 4500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateInvar>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickInvar>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 12550}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateIridium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickIridium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateIron>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickIron>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateMagnalium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickMagnalium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateManganese>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickManganese>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateMolybdenum>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickMolybdenum>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateNeodymium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickNeodymium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateNeutronium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickNeutronium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateOsmiridium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickOsmiridium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateOsmium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickOsmium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:platePalladium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickPalladium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateRedSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickRedSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateRoseGold>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickRoseGold>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateStainlessSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickStainlessSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateSterlingSilver>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickSterlingSilver>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 11250}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateTitanium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickTitanium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateTungsten>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickTungsten>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateTungstenSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickTungstenSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateUltimet>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickUltimet>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateVanadiumSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickVanadiumSteel>, null]]);
recipes.addShapeless(<contenttweaker:furnaceblock>, [<minecraft:furnace>]);
recipes.addShapeless(<gregtech:meta_item_1:2232>*8, [<gregtech:meta_item_1:2228>, <gregtech:meta_item_1:2094>, <gregtech:meta_item_1:2184>, <gregtech:meta_item_1:2184>, <gregtech:meta_item_1:2231>, <gregtech:meta_item_1:2231>, <gregtech:meta_item_1:2231>, <gregtech:meta_item_1:2231>]);
recipes.addShapeless(<gregtech:meta_item_1:2233>*8, [<gregtech:meta_item_1:2227>, <gregtech:meta_item_1:2230>, <gregtech:meta_item_1:2184>, <gregtech:meta_item_1:2184>, <gregtech:meta_item_1:2231>, <gregtech:meta_item_1:2231>, <gregtech:meta_item_1:2231>, <gregtech:meta_item_1:2231>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [<minecraft:stick>, <ore:toolHeadSawAluminium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [<minecraft:stick>, <tfc:metal/saw_blade/bismuth_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <ore:toolHeadSawBlackBronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <tfc:metal/saw_blade/black_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <tfc:metal/saw_blade/black_steel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/saw_blade/blue_steel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [<minecraft:stick>, <ore:toolHeadSawBrass>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <tfc:metal/saw_blade/bronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [<minecraft:stick>, <ore:toolHeadSawChrome>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "cobalt", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/saw_blade/cobalt>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [<minecraft:stick>, <ore:toolHeadSawCobaltBrass>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "copper", DigSpeed: 0.7 as float, MaxDurability: 300}}), [<minecraft:stick>, <tfc:metal/saw_blade/copper>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadSawDamascusSteel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [<minecraft:stick>, <ore:toolHeadSawDarmstadtium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadSawDiamond>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsse", MaxDurability: 19000}}), [<minecraft:stick>, <ore:toolHeadSawHsse>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hssg", MaxDurability: 17000}}), [<minecraft:stick>, <ore:toolHeadSawHssg>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsss", MaxDurability: 15000}}), [<minecraft:stick>, <ore:toolHeadSawHsss>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "invar", MaxDurability: 4500}}), [<minecraft:stick>, <tfc:metal/saw_blade/invar>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 10550}}), [<minecraft:stick>, <ore:toolHeadSawIridium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadSawIron>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/saw_blade/wrought_iron>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [<minecraft:stick>, <ore:toolHeadSawMagnalium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [<minecraft:stick>, <ore:toolHeadSawManganese>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadSawMolybdenum>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadSawNeodymium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [<minecraft:stick>, <ore:toolHeadSawNeutronium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [<minecraft:stick>, <ore:toolHeadSawOsmiridium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [<minecraft:stick>, <ore:toolHeadSawOsmium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [<minecraft:stick>, <ore:toolHeadSawPalladium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/saw_blade/red_steel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [<minecraft:stick>, <ore:toolHeadSawRoseGold>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadSawStainlessSteel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [<minecraft:stick>, <tfc:metal/saw_blade/steel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [<minecraft:stick>, <ore:toolHeadSawSterlingSilver>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadSawTitanium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [<minecraft:stick>, <ore:toolHeadSawTungsten>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [<minecraft:stick>, <ore:toolHeadSawTungstenSteel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [<minecraft:stick>, <ore:toolHeadSawUltimet>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [<minecraft:stick>, <ore:toolHeadSawVanadiumSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [<minecraft:stick>, <ore:toolHeadHammerAluminium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [<minecraft:stick>, <ore:toolHeadHammerBismuthBronze>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <ore:toolHeadHammerBlackBronze>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <ore:toolHeadHammerBlackSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadHammerBlueSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [<minecraft:stick>, <ore:toolHeadHammerBrass>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <ore:toolHeadHammerBronze>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [<minecraft:stick>, <ore:toolHeadHammerChrome>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadHammerCobalt>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [<minecraft:stick>, <ore:toolHeadHammerCobaltBrass>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "copper", DigSpeed: 0.7 as float, MaxDurability: 300}}), [<minecraft:stick>, <tfc:metal/hammer_head/copper>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadHammerDamascusSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [<minecraft:stick>, <ore:toolHeadHammerDarmstadtium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadHammerDiamond>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsse", MaxDurability: 19000}}), [<minecraft:stick>, <ore:toolHeadHammerHsse>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hssg", MaxDurability: 17000}}), [<minecraft:stick>, <ore:toolHeadHammerHssg>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsss", MaxDurability: 15000}}), [<minecraft:stick>, <ore:toolHeadHammerHsss>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "invar", MaxDurability: 4500}}), [<minecraft:stick>, <ore:toolHeadHammerInvar>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 10550}}), [<minecraft:stick>, <ore:toolHeadHammerIridium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadHammerIron>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [<minecraft:stick>, <ore:toolHeadHammerMagnalium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [<minecraft:stick>, <ore:toolHeadHammerManganese>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadHammerMolybdenum>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadHammerNeodymium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [<minecraft:stick>, <ore:toolHeadHammerNeutronium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [<minecraft:stick>, <ore:toolHeadHammerOsmiridium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [<minecraft:stick>, <ore:toolHeadHammerOsmium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [<minecraft:stick>, <ore:toolHeadHammerPalladium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadHammerRedSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [<minecraft:stick>, <ore:toolHeadHammerRoseGold>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadHammerStainlessSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [<minecraft:stick>, <ore:toolHeadHammerSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [<minecraft:stick>, <ore:toolHeadHammerSterlingSilver>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadHammerTitanium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [<minecraft:stick>, <ore:toolHeadHammerTungsten>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [<minecraft:stick>, <ore:toolHeadHammerTungstenSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [<minecraft:stick>, <ore:toolHeadHammerUltimet>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [<minecraft:stick>, <ore:toolHeadHammerVanadiumSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [<minecraft:stick>, <ore:toolHeadFileAluminium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [<minecraft:stick>, <ore:toolHeadFileBismuthBronze>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <ore:toolHeadFileBlackBronze>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <ore:toolHeadFileBlackSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadFileBlueSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [<minecraft:stick>, <ore:toolHeadFileBrass>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <ore:toolHeadFileBronze>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [<minecraft:stick>, <ore:toolHeadFileChrome>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadFileCobalt>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [<minecraft:stick>, <ore:toolHeadFileCobaltBrass>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadFileDamascusSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [<minecraft:stick>, <ore:toolHeadFileDarmstadtium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadFileDiamond>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsse", MaxDurability: 19000}}), [<minecraft:stick>, <ore:toolHeadFileHsse>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hssg", MaxDurability: 17000}}), [<minecraft:stick>, <ore:toolHeadFileHssg>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsss", MaxDurability: 15000}}), [<minecraft:stick>, <ore:toolHeadFileHsss>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "invar", MaxDurability: 4500}}), [<minecraft:stick>, <ore:toolHeadFileInvar>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 10550}}), [<minecraft:stick>, <ore:toolHeadFileIridium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadFileIron>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [<minecraft:stick>, <ore:toolHeadFileMagnalium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [<minecraft:stick>, <ore:toolHeadFileManganese>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadFileMolybdenum>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadFileNeodymium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [<minecraft:stick>, <ore:toolHeadFileNeutronium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [<minecraft:stick>, <ore:toolHeadFileOsmiridium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [<minecraft:stick>, <ore:toolHeadFileOsmium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [<minecraft:stick>, <ore:toolHeadFilePalladium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadFileRedSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [<minecraft:stick>, <ore:toolHeadFileRoseGold>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadFileStainlessSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [<minecraft:stick>, <ore:toolHeadFileSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [<minecraft:stick>, <ore:toolHeadFileSterlingSilver>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadFileTitanium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [<minecraft:stick>, <ore:toolHeadFileTungsten>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [<minecraft:stick>, <ore:toolHeadFileTungstenSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [<minecraft:stick>, <ore:toolHeadFileUltimet>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [<minecraft:stick>, <ore:toolHeadFileVanadiumSteel>]);

print("Initialized 'gregtech.zs'");